### ISSUE TITLE
What is the workflow of this template?

### ISSUE THREAD

**Issue by Waterkin** [piotr-rarus/python-template#60]
Hi, I have seen a lot tools in this template, but feel confused about how to integrate them into my workflow. How can I utilize them effectively?

**Comment by piotr-rarus** [comment]
@Waterkin Is there any specific problem you're having? I'd start just checking out every specific tool like `flake8`, `black`, `mypy` separately. Running them individually would be a bit cumbersome hence this template where we automate it using `pre-commit` and github actions. In some way it's already set up for you. `pre-commit` won't let you push incompatible changes. Additionally, I'd set protection rules against `main` branch so dev ones have to pass before merging.
